language: shell
os: linux

env:
  - HUGO_VERSION=0.69.2

before_install:
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o bin/hugo.tar.gz
  - tar xzvvf bin/hugo.tar.gz -C ./bin
  - export PATH=$PATH:`pwd`/bin
  - chmod +x build.sh
  - chmod +x deploy.sh
  - rm -rf public/*

script:
  - ./build.sh

deploy:
  on:
    branch: master
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  local_dir: public
  repo: fredrikbaberg/fredrikbaberg.github.io
  target_branch: master
  cleanup: true
  fqdn: baberg.nu
